networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  grafana-vol:

services:
  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
    networks:
      - monitoring
    expose:
      - "9100"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-vol:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus